version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Add other environment variables here
      # - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    restart: unless-stopped