branch-defaults:
  main:
    environment: trepidus-tech-prod
    group_suffix: null

global:
  application_name: trepidus-tech
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application