name: Test Application

on:
  push:
    branches-ignore:
      - main  # Main branch is handled by the aws-deploy.yml workflow
  pull_request:
    branches:
      - '**'  # Run on all PRs

env:
  NODE_VERSION: '20'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check types
      run: npm run check
      
    - name: Run linter (if available)
      run: npm run lint
      continue-on-error: true  # Won't fail the workflow if linting fails
      
    - name: Test API endpoints
      run: |
        npm run dev &
        sleep 10
        chmod +x ./tests/api.sh
        ./tests/api.sh
        pkill -f "npm run dev" || true

  build-test:
    name: Test Docker Build
    needs: lint-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: trepidus-tech-website:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Test Docker image
      run: |
        docker run -d -p 5000:5000 --name test-container trepidus-tech-website:test
        sleep 10
        curl -s http://localhost:5000/health | grep "healthy" || exit 1
        docker logs test-container
        docker stop test-container
        docker rm test-container